language: node_js
node_js: "14.15.3"
branches:
  only:
    - main
cache:
  directories:
    - node_modules
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS mknvh63jt0bx4odc'
test:
  - npm test
