language: node_js
node_js: 
 - "node"
branches:
  only:
    - master
    - main
cache:
  directories:
    - node_modules
services:
  - mysql

script:
  - true
  
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS mknvh63jt0bx4odc'
